# Customer Service OpenAPI Specification

openapi: 3.0.3
info:
  title: Customer Service API
  description: Customer management and registration service for the digital payment platform
  version: 1.0.0
  contact:
    name: Customer Service Team
    email: customer-service@payment-platform.com

servers:
  - url: http://localhost:8081/api/v1
    description: Local development server
  - url: https://api-dev.payment-platform.com/customer/v1
    description: Development environment
  - url: https://api.payment-platform.com/customer/v1
    description: Production environment

tags:
  - name: customers
    description: Customer registration and profile management
  - name: loyalty
    description: Customer loyalty program integration

paths:
  /customers:
    post:
      tags:
        - customers
      summary: Register new customer
      description: Register a new customer with automatic loyalty program enrollment
      operationId: registerCustomer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerRegistrationRequest"
            examples:
              valid_customer:
                summary: Valid customer registration
                value:
                  name: "John Doe"
                  phone: "+1-555-0123"
                  email: "john.doe@example.com"
                  iban: "GB29NWBK60161331926819"
      responses:
        "201":
          description: Customer registered successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerResponse"
        "400":
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
              examples:
                invalid_iban:
                  summary: Invalid IBAN format
                  value:
                    error: "VALIDATION_ERROR"
                    message: "Invalid IBAN format"
                    details:
                      ["IBAN must be a valid international bank account number"]
                    timestamp: "2026-02-13T10:30:00Z"
        "409":
          description: Customer already exists (phone or email)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    get:
      tags:
        - customers
      summary: Search customers
      description: Search customers by name, phone, or email
      operationId: searchCustomers
      parameters:
        - name: query
          in: query
          description: Search query (name, phone, or email)
          required: false
          schema:
            type: string
            example: "john"
        - name: page
          in: query
          description: Page number (0-based)
          required: false
          schema:
            type: integer
            default: 0
            example: 0
        - name: size
          in: query
          description: Page size
          required: false
          schema:
            type: integer
            default: 20
            maximum: 100
            example: 20
      responses:
        "200":
          description: Customer search results
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerSearchResponse"

  /customers/{customerId}:
    get:
      tags:
        - customers
      summary: Get customer by ID
      description: Retrieve customer profile information
      operationId: getCustomer
      parameters:
        - name: customerId
          in: path
          description: Customer ID
          required: true
          schema:
            type: integer
            format: int64
            example: 12345
      responses:
        "200":
          description: Customer profile
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerResponse"
        "404":
          description: Customer not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    put:
      tags:
        - customers
      summary: Update customer profile
      description: Update customer profile information (excluding IBAN for security)
      operationId: updateCustomer
      parameters:
        - name: customerId
          in: path
          description: Customer ID
          required: true
          schema:
            type: integer
            format: int64
            example: 12345
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerUpdateRequest"
      responses:
        "200":
          description: Customer updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerResponse"
        "400":
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Customer not found

  /customers/{customerId}/status:
    patch:
      tags:
        - customers
      summary: Update customer status
      description: Update customer account status (admin only)
      operationId: updateCustomerStatus
      parameters:
        - name: customerId
          in: path
          description: Customer ID
          required: true
          schema:
            type: integer
            format: int64
            example: 12345
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CustomerStatusUpdateRequest"
      responses:
        "200":
          description: Customer status updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CustomerResponse"
        "403":
          description: Insufficient permissions
        "404":
          description: Customer not found

  /customers/{customerId}/loyalty:
    get:
      tags:
        - loyalty
      summary: Get customer loyalty information
      description: Retrieve loyalty tier, points balance, and transaction history
      operationId: getCustomerLoyalty
      parameters:
        - name: customerId
          in: path
          description: Customer ID
          required: true
          schema:
            type: integer
            format: int64
            example: 12345
      responses:
        "200":
          description: Customer loyalty information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/LoyaltyInfoResponse"
        "404":
          description: Customer not found

  /customers/validate/iban:
    post:
      tags:
        - customers
      summary: Validate IBAN
      description: Validate IBAN format and check number
      operationId: validateIban
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IbanValidationRequest"
      responses:
        "200":
          description: IBAN validation result
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/IbanValidationResponse"

  /health:
    get:
      tags:
        - health
      summary: Health check
      description: Service health check endpoint
      operationId: healthCheck
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "UP"
                  timestamp:
                    type: string
                    format: date-time
                    example: "2026-02-13T10:30:00Z"

components:
  schemas:
    CustomerRegistrationRequest:
      type: object
      required:
        - name
        - phone
        - email
        - iban
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 100
          example: "John Doe"
          description: Customer full name
        phone:
          type: string
          pattern: '^\+[1-9]\d{1,14}$'
          example: "+1-555-0123"
          description: International phone number with country code
        email:
          type: string
          format: email
          example: "john.doe@example.com"
          description: Customer email address
        iban:
          type: string
          pattern: "^[A-Z]{2}[0-9]{2}[A-Z0-9]{1,30}$"
          example: "GB29NWBK60161331926819"
          description: International Bank Account Number

    CustomerUpdateRequest:
      type: object
      properties:
        name:
          type: string
          minLength: 2
          maxLength: 100
          example: "John Smith"
        email:
          type: string
          format: email
          example: "john.smith@example.com"

    CustomerStatusUpdateRequest:
      type: object
      required:
        - status
        - reason
      properties:
        status:
          type: string
          enum: [ACTIVE, INACTIVE, SUSPENDED]
          example: "SUSPENDED"
        reason:
          type: string
          maxLength: 500
          example: "Suspicious activity detected"

    CustomerResponse:
      type: object
      properties:
        customerId:
          type: integer
          format: int64
          example: 12345
        name:
          type: string
          example: "John Doe"
        phone:
          type: string
          example: "+1-555-0123"
        email:
          type: string
          example: "john.doe@example.com"
        status:
          type: string
          enum: [ACTIVE, INACTIVE, SUSPENDED]
          example: "ACTIVE"
        loyaltyTier:
          type: string
          enum: [SILVER, GOLD, PLATINUM]
          example: "SILVER"
        createdAt:
          type: string
          format: date-time
          example: "2026-02-13T10:30:00Z"
        lastUpdatedAt:
          type: string
          format: date-time
          example: "2026-02-13T10:30:00Z"

    CustomerSearchResponse:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/CustomerSummary"
        totalElements:
          type: integer
          format: int64
          example: 150
        totalPages:
          type: integer
          example: 8
        size:
          type: integer
          example: 20
        number:
          type: integer
          example: 0

    CustomerSummary:
      type: object
      properties:
        customerId:
          type: integer
          format: int64
          example: 12345
        name:
          type: string
          example: "John Doe"
        phone:
          type: string
          example: "+1-555-0123"
        email:
          type: string
          example: "john.doe@example.com"
        loyaltyTier:
          type: string
          enum: [SILVER, GOLD, PLATINUM]
          example: "SILVER"

    LoyaltyInfoResponse:
      type: object
      properties:
        customerId:
          type: integer
          format: int64
          example: 12345
        tier:
          type: string
          enum: [SILVER, GOLD, PLATINUM]
          example: "GOLD"
        pointsBalance:
          type: integer
          example: 2750
        tierProgress:
          $ref: "#/components/schemas/TierProgress"
        monthlyProgress:
          $ref: "#/components/schemas/MonthlyProgress"

    TierProgress:
      type: object
      properties:
        currentTier:
          type: string
          example: "GOLD"
        nextTier:
          type: string
          example: "PLATINUM"
        pointsNeeded:
          type: integer
          example: 12250
        progressPercentage:
          type: number
          format: double
          example: 18.33

    MonthlyProgress:
      type: object
      properties:
        pointsThisMonth:
          type: integer
          example: 450
        transactionsThisMonth:
          type: integer
          example: 12
        tierUpgradeEligible:
          type: boolean
          example: false

    IbanValidationRequest:
      type: object
      required:
        - iban
      properties:
        iban:
          type: string
          example: "GB29NWBK60161331926819"

    IbanValidationResponse:
      type: object
      properties:
        iban:
          type: string
          example: "GB29NWBK60161331926819"
        valid:
          type: boolean
          example: true
        countryCode:
          type: string
          example: "GB"
        bankCode:
          type: string
          example: "NWBK"
        accountNumber:
          type: string
          example: "60161331926819"

    ErrorResponse:
      type: object
      required:
        - error
        - message
        - timestamp
      properties:
        error:
          type: string
          example: "VALIDATION_ERROR"
          description: Error type code
        message:
          type: string
          example: "Invalid input data"
          description: Human-readable error message
        details:
          type: array
          items:
            type: string
          example: ["Name is required", "Invalid email format"]
          description: Detailed validation errors
        timestamp:
          type: string
          format: date-time
          example: "2026-02-13T10:30:00Z"
        path:
          type: string
          example: "/api/v1/customers"
          description: Request path that caused the error

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key for service authentication

    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for user authentication

security:
  - ApiKeyAuth: []
  - BearerAuth: []
